### ISSUE TITLE
Kwalitee complains about missing copyright on deleted file

### ISSUE THREAD

**Issue by jacquerie** [jirikuncar/kwalitee#55]
Kwalitee complains about a [missing copyright](http://kwalitee.invenio-software.org/inveniosoftware/invenio/branches/8426189a5b6325aa48912c35cf131a934ea714fc/jacquerie:kneczaj-rebase-and-update) on a [deleted file](https://github.com/inveniosoftware/invenio/pull/2752/files#diff-be011e6fce25e880eb7d21d323c5f230).

**Comment by jacquerie** [comment]
Thanks! May I push again to get rid of the spurious warning?

**Comment by jirikuncar** [comment]
You can try.
